version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_HOST: https://api.quicktecnologia.com
        NEXT_PUBLIC_SOCKET_URL: wss://api.quicktecnologia.com
        NEXT_PUBLIC_WEBSOCKET_URL: wss://api.quicktecnologia.com
        NEXT_PUBLIC_NEXTAUTH_API_HOST: https://api.quicktecnologia.com
    container_name: sistema-entrega-frontend
    restart: always
    ports:
      - "3001:3000"  # Mapeia porta 3001 do host para 3000 do container
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_HOST: https://api.quicktecnologia.com
      NEXT_PUBLIC_SOCKET_URL: wss://api.quicktecnologia.com
      NEXT_PUBLIC_WEBSOCKET_URL: wss://api.quicktecnologia.com
      NEXT_PUBLIC_NEXTAUTH_API_HOST: https://api.quicktecnologia.com
